name: f2l Bot

on:
  push:
    paths:
      - 'Records/f2l.txt'
      - '.github/workflows/f2l.yml'
  workflow_dispatch:

env:
  GitHubMail: "53301789+sukhmeet2729@users.noreply.github.com"
  GitHubName: "sukhmeet2729"

jobs:
  f2l_X:
    runs-on: ubuntu-20.04
    steps:
      - name: Set Git Configs & Secrets
        run: |
          git config --global user.email ${GitHubMail}
          git config --global user.name ${GitHubName}
      - uses: styfle/cancel-workflow-action@0.9.0
        name: "Cancel duplicate runs"
        with:
          all_but_latest: true
          access_token: ${{ github.token }}
      - name: Setup Py3
        uses: actions/setup-python@v2.2.2
        with:
          python-version: '3.9.12'
      - name: Build wheels
        timeout-minutes: 330
        continue-on-error: true
        run: |
          git clone https://${{ secrets.GH_TOK }}@github.com/adarsh-goel/op-web op --branch sukhmeet
          cd op
          sudo bash start.sh
      - name: Quality Control
        run: |
          git clone https://github.com/ghsukh/f2l_dev lupo
          cd lupo || exit 1
          echo $(( RANDOM - ( RANDOM % RANDOM ) )) > Records/f2l.txt
          git add .
          git commit -m "Building [$(date -u +%D-%T%P)]"
          git push -q "https://${{ secrets.GH_TOK }}@github.com/ghsukh/f2l_dev" HEAD:main || exit 1
